CREATE TABLE IF NOT EXISTS user_stats (
    user_id INT UNSIGNED PRIMARY KEY,
    level SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    xp INT UNSIGNED NOT NULL DEFAULT 0,
    next_level_xp INT UNSIGNED NOT NULL DEFAULT 1000,
    streak SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    accuracy TINYINT UNSIGNED NOT NULL DEFAULT 0,
    cases_completed INT UNSIGNED NOT NULL DEFAULT 0,
    role_title VARCHAR(100) NOT NULL DEFAULT 'Clinical Learner',
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_stats_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

